version: '3.4'

services:
  nginx:
    container_name: nginxsecureproxy
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/public:/var/www/public
      - ./certify/certbot/conf:/etc/letsencrypt/live
      - ./certify/certbot/webdata:/var/www/certbot
      - ./certify:/etc/certify
      - ./certify/log:/var/log/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: Dockerfile
      network: host