version: '3.4'

services:
  nginx:
    container_name: nginxsecureproxy
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/var/www
      - ./cert/certwebdata:/var/www/certbot
      - ./cert/certificates:/etc/letsencrypt/live
      - ./cert/log:/var/log/letsencrypt
      - ./cert/certifylog:/etc/certify/log
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: Dockerfile
      network: host