version: '3.4'

services:
  nginx:
    image: pthoelken/nginxsecureproxy
    container_name: nginxsecureproxy
    restart: always
    volumes:
      - ./nginxssl/nginx/conf.d:/etc/nginx/conf.d
      - ./nginxssl/nginx/www:/var/www
      - ./nginxssl/cert/certwebdata:/var/www/certbot
      - ./nginxssl/cert/certificates:/etc/letsencrypt/live
      - ./nginxssl/cert/log:/var/log/letsencrypt
      - ./nginxssl/cert/certifylog:/etc/certify/log
    ports:
      - "80:80"
      - "443:443"