version: '3.4'

services:
  nginx:
    container_name: nginxsecureproxy
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./public:/var/www/public
      - ./certbot/conf:/etc/letsencrypt/live
      - ./certbot/webdata:/var/www/certbot
      - ./certify:/etc/certify
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        - CERTBOT_EMAIL=${CERTBOT_MAIL}
        - DOMAIN_LIST=${DOMAINLIST}

# networks:
#   default:
#     external: true
#     name: nginxproxy