#!/bin/bash

strDate=$(date +%Y-%m-%d)

strCertifyBaseFolder=/etc/certify

strCertifyConfigFolder=$strCertifyBaseFolder/configs
strCertifyDefaultConfig=$strCertifyConfigFolder/foo.bar.conf
strNginxConfigPath=/etc/nginx/conf.d
strExampleDomainName=example.org

strCertifyDomainFolder=$strCertifyBaseFolder/domains
strCertifyLogFolder=$strCertifyBaseFolder/log
strCertifyLogFinalPath=$strCertifyLogFolder/certify_$strDate.log

strDomainName=""

function Logger() {

    if [ ! -f $strCertifyLogFinalPath ]; then
        touch $strCertifyLogFinalPath
    fi 

    echo -e "$strDate || $1" >> $strCertifyLogFinalPath

}

if [ ! -z "$(ls -A $strCertifyDomainFolder )" ]; then
    for strFileName in $strCertifyDomainFolder/*.*; do
        strDomainName=$(basename $strFileName)
        strMailAddress=$(head -n 1 $strFileName)

        # strCertBotOrigin=/var/www/certbot
        strCertbotWebDir=/var/www/certbot/$strDomainName
        mkdir -p $strCertbotWebDir
        chown -R nginx:nginx /var/www/

        strDefaultNginxConfig=/etc/nginx/conf.d/80-default.conf
        strOriginString=/var/www/certbot
        strNewString=/var/www/certbot/$strDomainName
        
        sed -i "s#$strOriginString#$strNewString#g" $strDefaultNginxConfig
        /etc/init.d/nginx restart

        certbot certonly --non-interactive --webroot --webroot-path=$strCertbotWebDir --email $strMailAddress --agree-tos --no-eff-email -d $strDomainName

        sed -i "s#$strNewString#$strOriginString#g" $strDefaultNginxConfig
        /etc/init.d/nginx restart
       
        cp $strCertifyDefaultConfig $strNginxConfigPath/$strDomainName
        sed -i 's/'$strExampleDomainName'/'$strDomainName'/g' $strNginxConfigPath/$strDomainName

        mv $strNginxConfigPath/$strDomainName $strNginxConfigPath/$strDomainName.conf

        /etc/init.d/nginx restart

        rm -rf $strFileName
    done
fi