name: CI for Docker Building and Push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Hub login
      - env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Run a one-line script
        run: docker build -t pthoelken/nginxsecureproxy:latest .
      - name: Docker Push Image to Docker Hub
        run: docker push pthoelken/nginxsecureproxy:latest